fix: trigger aligned timerule when diff is equal to period
MathisWellmann/trade_aggregation-rs pull request #17
Opened 2024-04-09 10:43 UTC by ivaaaan

Aligned time rule is not triggered on timestamps like `15:00:00` with one minute rule

2024-04-09 16:40 UTC, MathisWellmann requested changes
Looks good overall. Some slight test modifications and we can get this merged.

2024-04-09 16:40 UTC, MathisWellmann commented on src/aggregation_rules/aligned_time_rule.rs
> +            },
```suggestion
            Trade {
                timestamp: 1712656815000,
                price: 100.5,
                size: 10.0,
            },
            Trade {
                timestamp: 1712656860000,
                price: 101.0,
                size: -10.0,
            },
```
Would be good for both prices to be unique.

2024-04-09 16:40 UTC, MathisWellmann commented on src/aggregation_rules/aligned_time_rule.rs
> +        assert_eq!(candles[1].open(), 101.00);
```suggestion
        assert_eq!(candles[0].open(), 100.0);
        assert_eq!(candles[0].close(), 100.5);
        assert_eq!(candles[1].open(), 101.0);
        assert_eq!(candles[1].close(), 101.0);
```
An assertion for the close price would be good as well.
I think those values are correct, but unfortunate that both open and close prices are 101, so maybe it makes sense to add another trade to be included in the second candle

2024-04-10 09:29 UTC, ivaaaan commented
@MathisWellmann updated this one as well

2024-04-10 10:11 UTC, MathisWellmann approved these changes

2024-04-10 10:11 UTC, merged